
// behavior ids
enum {
//	VB_DEFAULT=1,
	VB_PANEL=1,
	VB_SCROLLVIEW,
	VB_INVENTORY,
	VB_TELETYPE,
	VB_TEXTVIEW,
	VB_SURROUND,
	VB_COMPASS,
	VB_CTRLVIEW,
	VB_CFGNET,
	VB_CFGPLYR,
	VB_CFGGAME,
	VB_CFGAV,
};

#define SURROUND_MASK	"surround.vct"
#define TELETYPE_MASK	"combox.vct"
#define INVENTORY_MASK	"inventory.vct"
#define ID_MASK		"myid.vct"
#define OTHERID_MASK	"otherid.vct"
#define WORLDID_MASK	"worldid.vct"
#define NYMETER_MASK	"vialmtr.vct"
#define COMPASS_MASK	"compass.vct"
#define PANEL_MASK	"smlpanel.vct"
#define PANARAMA_MASK	"wdepanel.vct"

#define PLAYERNAME_MASK	"myname.vct"
#define OTHERNAME_MASK	"othrname.vct"
#define HOUSEICON_MASK	"housicon.vct"

#define CFG_WIDE(MUSIC, CFG_CLASS) \
    1, MUSIC, VC_VIEWSCREEN, CFG_CLASS, PANARAMA_MASK

#define STD_SURR(MUSIC) \
    1, MUSIC, VC_VIEWSCREEN, VB_SURROUND, SURROUND_MASK

#define STD_PANL(MUSIC) \
    1, MUSIC, VC_VIEWSCREEN, VB_PANEL, PANEL_MASK

#define STD_SCRL(MUSIC) \
    1, MUSIC, VC_VIEWSCREEN, VB_SCROLLVIEW,	PANEL_MASK

#define STD_WIDESCRL(MUSIC) \
    1, MUSIC, VC_VIEWSCREEN, VB_SCROLLVIEW,	PANARAMA_MASK

#define STD_WIDE(MUSIC) \
    1,MUSIC, VC_VIEWSCREEN, VB_PANEL, PANARAMA_MASK

#define VID(ID) ID, #ID

static VIEW_DESCRIPTION s_tbl_views[] = {
	// view ID,  Map (see above), Z order,  
	{VID(IDV_MAIN_PANEL),0,0,0, VB_PANEL,"mpmask.vct","GUI"},
	{VID(IDV_INVENTORY),	1,0,0, VB_INVENTORY,INVENTORY_MASK, "inventor"},
	{VID(IDV_ID),		1,0,0, VB_PANEL, ID_MASK, "id"},
	{VID(IDV_OTHERID),	1,0,0, VB_PANEL, OTHERID_MASK, "you"},
	{VID(IDV_COMPASS),	1,0,0, VB_COMPASS, COMPASS_MASK, "compass"},
	{VID(IDV_S_TELETYPE),1,0,0, VB_TELETYPE, TELETYPE_MASK, "teletype"},
	{VID(IDV_PLAYERNAME),1,0,0, VB_CTRLVIEW,PLAYERNAME_MASK,"namefill"},
	{VID(IDV_OTHERNAME),	1,0,0, VB_CTRLVIEW,OTHERNAME_MASK,"namefill"},

	{VID(IDV_TOPMENU),	STD_SURR(THEME), "spacemen"},
	{VID(IDV_CFGPROV),	CFG_WIDE(THEME, VB_CFGNET), "spacebak"},
	{VID(IDV_CFGSESS),	CFG_WIDE(THEME, VB_CFGNET), "spacebak"},
	{VID(IDV_CFGNEWSESS),	CFG_WIDE(THEME, VB_CFGNET), "spacebak"},

	{VID(IDV_CFGPLAYER1),	CFG_WIDE(THEME, VB_CFGPLYR), "spacebak"},
	{VID(IDV_CFGPLAYER2),	CFG_WIDE(THEME, VB_CFGPLYR), "spacebak"},

	{VID(IDV_CFGGAME),	CFG_WIDE(THEME, VB_CFGGAME), "spacebak"},

	{VID(IDV_CFGAV),	CFG_WIDE(THEME, VB_CFGAV), "spacebak"},

	{VID(IDV_CONTINENT),	STD_WIDESCRL(THEME), "contin~1"},

	// Scene 2:

	{VID(IDV_LOCKERR),	STD_SURR(CITY), "lockerS"},
	{VID(IDV_LOCKERN),	STD_PANL(CITY), "lockerSw"},
	{VID(IDV_LOCKERW),	STD_PANL(CITY), "lockerSw"},
	{VID(IDV_LOCKERS),	STD_PANL(CITY), "lockerSw"},

#define LOCKER_CLOSEUP(ID) {VID(IDV_LOCKERCU+ID),STD_PANL(CITY),"lockercu"}
	LOCKER_CLOSEUP(0),
	LOCKER_CLOSEUP(1),
	LOCKER_CLOSEUP(2),
	LOCKER_CLOSEUP(3),
	LOCKER_CLOSEUP(4),
	LOCKER_CLOSEUP(5),
	LOCKER_CLOSEUP(6),
	LOCKER_CLOSEUP(7),
	LOCKER_CLOSEUP(8),

	LOCKER_CLOSEUP(9),
	LOCKER_CLOSEUP(10),
	LOCKER_CLOSEUP(11),
	LOCKER_CLOSEUP(12),
	LOCKER_CLOSEUP(13),
	LOCKER_CLOSEUP(14),
	LOCKER_CLOSEUP(15),
	LOCKER_CLOSEUP(16),
	LOCKER_CLOSEUP(17),

	LOCKER_CLOSEUP(18),
	LOCKER_CLOSEUP(19),
	LOCKER_CLOSEUP(20),
	LOCKER_CLOSEUP(21),
	LOCKER_CLOSEUP(22),
	LOCKER_CLOSEUP(23),
	LOCKER_CLOSEUP(24),
	LOCKER_CLOSEUP(25),
	LOCKER_CLOSEUP(26),

	//city surround views	
	{VID(IDV_ctya),	STD_SURR(CITY), "ctya"},
	{VID(IDV_ctyb),	STD_SURR(CITY), "ctyb"},
	{VID(IDV_ctyc),	STD_SURR(CITY), "ctyc"},
	{VID(IDV_ctyd),	STD_SURR(CITY), "ctyd"},
	{VID(IDV_ctye),	STD_SURR(CITY), "ctye"},
	{VID(IDV_ctyf),	STD_SURR(CITY), "ctyf"},
	{VID(IDV_ctyg),	STD_SURR(CITY), "ctyg"},
	{VID(IDV_ctyh),	STD_SURR(CITY), "ctyh"},
	{VID(IDV_ctyi),	STD_SURR(CITY), "ctyi"},
	{VID(IDV_ctyj),	STD_SURR(CITY), "ctyj"},
	{VID(IDV_ctyk),	STD_SURR(CITY), "ctyk"},
	{VID(IDV_ctyl),	STD_SURR(CITY), "ctyl"},
	{VID(IDV_ctym),	STD_SURR(CITY), "ctym"},
	{VID(IDV_ctyn),	STD_SURR(CITY), "ctyn"},
	{VID(IDV_ctyo),	STD_SURR(CITY), "ctyo"},
	{VID(IDV_ctyp),	STD_SURR(CITY), "ctyp"},
	{VID(IDV_ctyq),	STD_SURR(CITY), "ctyq"},
	{VID(IDV_ctyr),	STD_SURR(CITY), "ctyr"},
	{VID(IDV_ctys),	STD_SURR(CITY), "ctys"},
	{VID(IDV_ctyt),	STD_SURR(CITY), "ctyt"},


	//city locksmith 
	{VID(IDV_ctysmith),		STD_SURR(CITY), "ctysmith"},
	{VID(IDV_ckeycf01),		STD_PANL(CITY), "ckeycf01"},
	{VID(IDV_ckeycf02),		STD_PANL(CITY), "ckeycf01"},
	{VID(IDV_ckeycf03),		STD_PANL(CITY), "ckeycf01"},
	{VID(IDV_ckeyvend),		STD_PANL(CITY), "ckeyvend"},

	//city housing
	{VID(IDV_ctyhouse),		STD_SURR(CITY), "ctyhouse"},
	{VID(IDV_chouse01),		STD_PANL(CITY), "chouse1"},
	{VID(IDV_chouse02),		STD_PANL(CITY), "chouse2"},
	{VID(IDV_chouse03),		STD_PANL(CITY), "chouse3"},

	// Scene 05: Chem Lab 101.
	{VID(IDV_ctychem),		STD_SURR(CITY), "ctychem"},
	{VID(IDV_chempan),		STD_PANL(CITY), "chempan"},

	// Scene 06: CITY LIBRARY & Pez hell.
	{VID(IDV_CTYLIB1A),		STD_SURR(CITY), "ctylib1a"},
	{VID(IDV_CTYLIB1B),		STD_SURR(CITY), "ctylib1b"},
	{VID(IDV_CTYLIB2A),		STD_SURR(CITY), "ctylib2a"},
	{VID(IDV_CTYLIB2B),		STD_SURR(CITY), "ctylib2b"},

	{VID(IDV_CLIBMON1),		STD_PANL(CITY), "MONITOR"},
	{VID(IDV_CLIBMON2),		STD_PANL(CITY), "MONITOR"},
	{VID(IDV_CLIBMON3),		STD_PANL(CITY), "MONITOR"},
	{VID(IDV_CLIBMON4),		STD_PANL(CITY), "MONITOR"},
	{VID(IDV_CLIBMON5),		STD_PANL(CITY), "MONITOR"},
	{VID(IDV_CLIBMON6),		STD_PANL(CITY), "MONITOR"},
	{VID(IDV_CLIBMUS1),		STD_PANL(CITY), "CLIBMUS1"},
	{VID(IDV_CLIBMUS2),		STD_PANL(CITY), "CLIBMUS2"},

	{VID(IDV_CTYPEZ1),		STD_PANL(CITY), "PEZPAN1"},
	{VID(IDV_CTYPEZ2),		STD_PANL(CITY), "PEZPAN2"},
	{VID(IDV_CTYPEZ3),		STD_PANL(CITY), "PEZPAN3"},
	{VID(IDV_CTYPEZ4),		STD_PANL(CITY), "PEZPAN4"},
	{VID(IDV_CTYPEZ5),		STD_PANL(CITY), "PEZPAN5"},
	{VID(IDV_CTYPEZ6),		STD_PANL(CITY), "PEZPAN6"},
	{VID(IDV_CTYPEZ7),		STD_PANL(CITY), "PEZPAN7"},

	{VID(IDV_ctytrade),		STD_SURR(CITY), "ctytrade"},

	{VID(IDV_MANPAN),		STD_SURR(CITY), "MANPAN"},
	{VID(IDV_MANREP1),	STD_PANL(CITY), "manrep"},
	{VID(IDV_MANREP2),	STD_PANL(CITY), "manrep"},
	{VID(IDV_MANREP3),	STD_PANL(CITY), "manrep"},
	{VID(IDV_MANREP4),	STD_PANL(CITY), "manrep"},
	{VID(IDV_MANREP5),	STD_PANL(CITY), "manrep"},
	{VID(IDV_MANREP6),	STD_PANL(CITY), "manrep"},
	{VID(IDV_MANREP7),	STD_PANL(CITY), "manrep"},
	{VID(IDV_MANREP8),	STD_PANL(CITY), "manrep"},
	{VID(IDV_MANREP9),	STD_PANL(CITY), "manrep"},
	{VID(IDV_MANREP10),	STD_PANL(CITY), "manrep"},
	{VID(IDV_MANFUR),	STD_PANL(CITY), "manrep"},
	{VID(IDV_STRATPAN),		STD_SURR(CITY), "STRATPAN"},
	{VID(IDV_STRATMON1),	1,CITY, VC_VIEWSCREEN, VB_CTRLVIEW,PANARAMA_MASK,"STRATMON"},
	{VID(IDV_STRATMON2),	1,CITY, VC_VIEWSCREEN, VB_CTRLVIEW,PANARAMA_MASK,"STRATMON"},

	{VID(IDV_STRATMAP),	2,CITY, 0, VB_SCROLLVIEW,"monmask.vct","contin~1"},

	{VID(IDV_FA1PAN),		STD_SURR(NATURE), "fa1pan"},
	{VID(IDV_FH1PAN),		STD_SURR(NATURE), "fh1pan"},

	{VID(IDV_GRBDRT1),		STD_PANL(NATURE), "grbdrt1"},
	{VID(IDV_GRBDRT2),		STD_PANL(NATURE), "grbdrt2"},

	{VID(IDV_FH1PTH1),		STD_SURR(NATURE), "FH1PTH1"},
	{VID(IDV_FH1PTH2),		STD_SURR(NATURE), "FH1PTH2"},

//DRYPIT
	{VID(IDV_SCN10PT0),		STD_SURR(THEME), "SCN10PT0"},
	{VID(IDV_SCN10PIT),		STD_PANL(THEME), "SCN10PIT"},


	// Scene 12
	{VID(IDV_TM1PAN),		STD_SURR(THEME), "TM1pan"},
	{VID(IDV_TM2PAN),		STD_SURR(THEME), "TM2pan"},
	{VID(IDV_VESTPAN1),		STD_WIDE(THEME), "VESTPAN"},
	{VID(IDV_VESTPAN2),		STD_WIDE(THEME), "VESTPAN"},
	{VID(IDV_TM3PAN),		STD_SURR(THEME), "TM3pan"},
	{VID(IDV_TM4PAN),		STD_SURR(THEME), "TM4pan"},
	{VID(IDV_TM5PAN),		STD_SURR(THEME), "TM5pan"},
	{VID(IDV_TMCU1),		STD_PANL(THEME), "TMCU1"},
	{VID(IDV_TMCU2),		STD_PANL(THEME), "TMCU2"},
	{VID(IDV_TMCU3),		STD_PANL(THEME), "TMCU3"},
	{VID(IDV_TMCU4),		STD_PANL(THEME), "TMCU4"},
	{VID(IDV_TMCUT),		STD_WIDE(THEME), "TMCUT"},

	//SCENE 13: VILLAGE 

	{VID(IDV_VIL2),		STD_SURR(VILLAGE), "vil2"},
	{VID(IDV_VIL3),		STD_SURR(VILLAGE), "vil3"},
	{VID(IDV_VIL4),		STD_SURR(VILLAGE), "vil4"},
	{VID(IDV_VIL5),		STD_SURR(VILLAGE), "vil5"},
	{VID(IDV_VIL6),		STD_SURR(VILLAGE), "vil6"},
	{VID(IDV_VIL7),		STD_SURR(VILLAGE), "vil7"},
	{VID(IDV_VIL8),		STD_SURR(VILLAGE), "vil8"},
	{VID(IDV_VIL9),		STD_SURR(VILLAGE), "vil9"},
	{VID(IDV_VILA),		STD_SURR(VILLAGE), "vila"},
	{VID(IDV_VILB),		STD_SURR(VILLAGE), "vilb"},
	{VID(IDV_VILC),		STD_SURR(VILLAGE), "vilc"},
	{VID(IDV_VILD),		STD_SURR(VILLAGE), "vild"},
	{VID(IDV_VILE),		STD_SURR(VILLAGE), "vile"},
	//{VID(IDV_VILF),		STD_SURR(VILLAGE), "vilf"},
	{VID(IDV_VILG),		STD_SURR(VILLAGE), "vilg"},
	{VID(IDV_VILH),		STD_SURR(VILLAGE), "vilh"},
	{VID(IDV_VILI),		STD_SURR(VILLAGE), "vili"},
	//{VID(IDV_VILJ),		STD_SURR(VILLAGE), "vilj"},
	{VID(IDV_VILK),		STD_SURR(VILLAGE), "vilk"},
	{VID(IDV_VILL),		STD_SURR(VILLAGE), "vill"},
	{VID(IDV_VILM),		STD_SURR(VILLAGE), "vilm"},
	{VID(IDV_VILN),		STD_SURR(VILLAGE), "viln"},
	{VID(IDV_VILO),		STD_SURR(VILLAGE), "vilo"},
	//{VID(IDV_VILP),		STD_SURR(VILLAGE), "vilp"},
	//{VID(IDV_VILQ),		STD_SURR(VILLAGE), "vilq"},
	//{VID(IDV_VILR),		STD_SURR(VILLAGE), "vilr"},


	// Scene 15:
	{VID(IDV_TMPLPTH1),		STD_SURR(VILLAGE), "tmplpth1"},
	{VID(IDV_TMPLPTH2),		STD_SURR(VILLAGE), "tmplpth2"},
	{VID(IDV_TMPLPTH3),		STD_SURR(VILLAGE), "tmplpth3"},
	{VID(IDV_TMPLPTH4),		STD_SURR(VILLAGE), "tmplpth4"},
	{VID(IDV_TMPLPTH5),		STD_SURR(VILLAGE), "tmplpth5"},
	{VID(IDV_TMPLPTH6),		STD_SURR(VILLAGE), "tmplpth6"},
	{VID(IDV_TMPLPTH7),		STD_SURR(VILLAGE), "tmplpth7"},
	{VID(IDV_TMPLPTH8),		STD_SURR(VILLAGE), "tmplpth8"},
	{VID(IDV_TMPLPTH9),		STD_SURR(VILLAGE), "tmplpth9"},

	{VID(IDV_GRNDCNT1),		STD_SURR(THEME), "GRNDCNT1"},

	// quarry
	{VID(IDV_QUARSA),		STD_SURR(THEME), "QUARSA"},
	{VID(IDV_QUARSB),		STD_SURR(THEME), "QUARSB"},

	// standing in front of a mine panel (there are 5 mines)
	{VID(IDV_aMINEPAN),	STD_WIDE(THEME), "MINEPAN1"},
	// inside the entry of the mine
	{VID(IDV_aCV1aPAN),	STD_SURR(THEME), "CV1a"},
	// deep in the mine,  at the nystrom
	{VID(IDV_aCV1bPAN),	STD_SURR(THEME), "CV1b"},

	// rest of the mines ...
	{VID(IDV_bMINEPAN),	STD_WIDE(NATURE), "MINEPAN1"},
	{VID(IDV_bCV1aPAN),	STD_SURR(NATURE), "CV1a"},
	{VID(IDV_bCV1bPAN),	STD_SURR(NATURE), "CV1b"},
	{VID(IDV_cMINEPAN),	STD_WIDE(NATURE), "MINEPAN1"},
	{VID(IDV_cCV1aPAN),	STD_SURR(NATURE), "CV1a"},
	{VID(IDV_cCV1bPAN),	STD_SURR(NATURE), "CV1b"},
	{VID(IDV_dMINEPAN),	STD_WIDE(THEME), "MINEPAN1"},
	{VID(IDV_dCV1aPAN),	STD_SURR(NATURE), "CV2a"},
	{VID(IDV_dCV1bPAN),	STD_SURR(NATURE), "CV2b"},
	{VID(IDV_eMINEPAN),	STD_WIDE(NATURE), "MINEPAN1"},
	{VID(IDV_eCV1aPAN),	STD_SURR(NATURE), "CV2a"},
	{VID(IDV_eCV1bPAN),	STD_SURR(NATURE), "CV2b"},

	{VID(IDV_NAT1a),	STD_SURR(NATURE), "nat1a"},
	{VID(IDV_NAT1b),	STD_SURR(NATURE), "nat1b"},
	{VID(IDV_NAT1c),	STD_SURR(NATURE), "nat1c"},
	{VID(IDV_NAT1d),	STD_SURR(NATURE), "nat1d"},
	{VID(IDV_NAT1e),	STD_SURR(NATURE), "nat1e"},
	{VID(IDV_NAT1f),	STD_SURR(NATURE), "nat1f"},
	{VID(IDV_NAT1g),	STD_SURR(NATURE), "nat1g"},
	{VID(IDV_NAT1h),	STD_SURR(NATURE), "nat1h"},
	{VID(IDV_NAT1i),	STD_SURR(NATURE), "nat1i"},
	{VID(IDV_NAT1j),	STD_SURR(NATURE), "nat1j"},
	{VID(IDV_NAT1k),	STD_SURR(NATURE), "nat1k"},
	{VID(IDV_NAT1l),	STD_SURR(NATURE), "nat1l"},
	{VID(IDV_NAT1m),	STD_SURR(NATURE), "nat1m"},
	{VID(IDV_NAT1n),	STD_SURR(NATURE), "nat1n"},
	{VID(IDV_NAT1o),	STD_SURR(NATURE), "nat1o"},
	{VID(IDV_NAT1p),	STD_SURR(NATURE), "nat1p"},

	{VID(IDV_PARCHPAN),	STD_WIDE(THEME), "PARCHPAN"},

	{VID(IDV_EYEA),	STD_SURR(THEME), "eyea"},
	{VID(IDV_EYEB),	STD_SURR(THEME), "eyeb"},
	{VID(IDV_EYEC1P),	STD_WIDE(THEME), "eyec1p"},
	

	{VID(IDV_WR1),	STD_SURR(NATURE), "WR1"},
	{VID(IDV_WR2),	STD_SURR(NATURE), "WR2"},
	{VID(IDV_WR3),	STD_SURR(NATURE), "WR3"},
	{VID(IDV_W4LOCK),	STD_WIDE(THEME), "W4LOCK"},
	{VID(IDV_WALL1EN),	STD_SURR(THEME), "WALL1EN"},
	{VID(IDV_WALL1IN),	STD_SURR(THEME), "WALL1IN"},
	{VID(IDV_WALL2EN),	STD_SURR(THEME), "WALL2EN"},
	{VID(IDV_WALL2IN),	STD_SURR(THEME), "WALL2IN"},
	{VID(IDV_PL1P),	STD_WIDE(THEME), "PL1P"},
	{VID(IDV_PL2P),	STD_WIDE(THEME), "PL2P"},
	{VID(IDV_HIDDENR1),	STD_SURR(THEME), "HIDDENR1"},
	{VID(IDV_HIDDENR2),	STD_SURR(THEME), "HIDDENR2"},


	{VID(IDV_BANISH),	STD_SURR(NATURE), "BANISH"},

	// do not add anything below the board ...
	{VID(IDV_BOARD),	STD_SURR(THEME), "board"},
};

