#!/bin/sh

cp pit00.png pitful.png
./onepng pitful.png -a pit01.png pitful.png
./onepng pitful.png -a pit02.png pitful.png
./onepng pitful.png -a pit03.png pitful.png
./onepng pitful.png -a pit04.png pitful.png
./onepng pitful.png -a pit05.png pitful.png
./onepng pitful.png -a pit06.png pitful.png
./onepng pitful.png -a pit07.png pitful.png
./onepng pitful.png -a pit08.png pitful.png
./onepng pitful.png -a pit09.png pitful.png
./onepng pitful.png -a pit11.png pitful.png
./onepng pitful.png -a pit12.png pitful.png
./onepng pitful.png -a pit13.png pitful.png
./onepng pitful.png -a pit14.png pitful.png
./onepng pitful.png -a pit15.png pitful.png
./onepng pitful.png -a pit16.png pitful.png
./onepng pitful.png -a pit17.png pitful.png
./onepng pitful.png -a pit18.png pitful.png
./onepng pitful.png -a pit19.png pitful.png
